platform :ios, '8.4'

#//通过指定use_frameworks!要求生成的是framework而不是静态库
#use_frameworks!

#//在全局指定不显示所有所引用的库中的警告信息
inhibit_all_warnings!

target 'CSKit' do

pod 'AFNetworking'#, '~> 3.0.4'
pod 'MJRefresh'

end
